version: '3'
services:
  node:
    build: ./node_app
    image: creativepassport/artist-hub-node
    restart: always
    env_file: ./node_app/.env
    ports:
      - "4000:4000"
  web:
    build: ./web_app
    image: creativepassport/artist-hub-web
    restart: always
    environment:
      API_HOST: node:4000
    ports:
      - "127.0.0.1:3000:80"
