version: '3'
services:
  node:
    environment:
      PGDATABASE: artisthub
      PGHOST: db
      PGPORT: 5432
      PGUSER: artisthub
      PGPASSWORD: password
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12.6
    restart: always
    volumes:
      - artisthub-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U artisthub"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: artisthub
      POSTGRES_DB: artisthub

volumes:
  artisthub-postgres:
